; USB Upload (Erstflash / Fallback)
[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
upload_speed = 921600

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.3
  knolleary/PubSubClient @ ^2.8

; OTA Upload (kabellos!)
; Usage: pio run -e ota --target upload
[env:ota]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

upload_protocol = espota
upload_port = meetingroom-display.local
upload_flags =
  --auth=microbots

lib_deps =
  bblanchon/ArduinoJson @ ^7.4.3
  knolleary/PubSubClient @ ^2.8
